### ISSUE TITLE
Random HQ, zone placement and side missions do not work with ACE 3 enabled. 

### ISSUE THREAD

**Issue by FoxWolf45** [DUWS-R-Team/DUWS-R#106]
Greetings there.

Recently I have been trying to mod my experience of DUWS-R by playing with a friend and modding in ACE 3 and other modifications. When starting a listen server, hosted on my computer, we came across the problem that random generation does not work at all.

warning: We have not tested this on a dedicated server and that needs confirmation.

When manually creating the HQ location and manually setting up all the enemy zones, things seem to work okay, though when choosing a side mission, the game simply freezes on the loading screen and the game has to be forcefuly closed.

By process of elimination, we removed the mods and slowly went through them and realized the culprit was the ACE 3 mod. I assumed that it was one of the modules causing the problems, like AI, weather generation. Some modules can be removed easily, but the problem still persists and I can't pinpoint what module or calculation in ACE 3's logic would be causing this compatibility issue.

On the note of weather generaton, disabling dynamic weather in DUWS-R's campaign generation does not solve the problem.

The reason could be that ACE 3 is fairly new and there will surely be compatibility issues, but I am posting this here either way, as it has not been mentioned yet in the issues section.

STEPS TAKEN TO REPRODUCE ISSUE:
1. Enable the ACE 3 mod and the required modifications (Community base addons) to run it in the launcher or through the starting parameters
2. In the main menu go into multiplayer and host a new game with DUWS-R. You can do it by yourself or with a friend.
3. Start the session and wait for it to load.
4. At the beginning you spawn like always on the lower left edge of the map and the HQ generation querry window appears. Press on the random button.
5. The game waits a bit and nothing happens, the user needing to force a restart of the map.

Thank you in forward for any help regarding this issue.

**Comment by fritogotlayed** [comment]
@FoxWolf45 Thanks for creating the issue. I'm not familiar with ACE 3 at all so I really don't have any tips off the top of my head. Have you tried creating a fork and playing around in the ArmA3 editor with the mods enabled? I forget exactly where but the engine will output errors like missing variables and the such. It might help to track down what is going on between DUWS-R and ACE3.

**Comment by FoxWolf45** [comment]
Greetings there again.

I have been experimenting a bit further and I have found the issue that I have been talking about. ACE3 has a file called map.pbo and it's bikey file in addition to that.

The addon causes the map to show roads and elevation lines more distinctively on Altis.
Due to the changes on the map I assume that DUWS when trying to generate the random base location and areas is unable to properly read the map. It probably acts the same when trying to run DUWS on another map like for example Stratis without editing the .pbo

Doing multiple tries and experimentation, the culprit is indeed the map.pbo addon in ACE 3's addon file.

The extent of this issue is minimal, as users can easily remove the map.pbo addon and this can be solved later by communicating with ACE 3's devs regarding that or editing DUWS-R's .pbo to accept the changes to the map.

**Comment by cookingboy3** [comment]
This bug remains.
