### ISSUE TITLE
DUWS-R-0.2.0 armory issue

### ISSUE THREAD

**Issue by dgrrr** [DUWS-R-Team/DUWS-R#115]
Should I assume "DUWS-R-0.2.0" is some kind of beta, and "DUWS-R-0.1.0" is the main release?

I'm trying "DUWS-R-0.2.0" and FYI the armory is not working - I can't load or remove items, and when I load a loadout from vanilla DUWS it strips me to my t shirt.

**Comment by fritogotlayed** [comment]
@dgrrr Where are you seeing "DUWS-R-0.2.0"? If you're referring to the tag "v.0.2.0" then that's an older version. The latest version of the mission is at HEAD (hash 5b55746). I apologize but I'm not sure what you're asking. As always, feel free to drop in on the IRC if you don't want to trade emails back and forth :smiley:

**Comment by fritogotlayed** [comment]
https://webchat.freenode.net/ if you wanted the link
