### ISSUE TITLE
Sling loading issue

### ISSUE THREAD

**Issue by jamwaddell** [DUWS-R-Team/DUWS-R#117]
Rope doesn't drop when sling loading is used with helicopters in multiplayer, therefore you can't seem to sling load any vehicles for transport.

**Comment by fritogotlayed** [comment]
@jamwaddell I really appreciate you creating the issue. I really don't have the time / life bandwidth to continue supporting DUWS-R though so I don't know when this would get resolved. If you are interested I am looking for someone to take over DUWS-R. Assuming that is something you would like to take on I can transfer the DUWS-R-Team over and figure out what needs to be done on Steam. Would you like to take over DUWS-R?

**Comment by jamwaddell** [comment]
Hey there. I actually am not sure I have time for full time development on
this myself (I currently do a lot of full-time development for an
automation company that eats most of my day), and I apologize for bringing
this up then. I didn't know you were looking to hand this off, sorry about
that. I'll consider it though and get back to you, or at least see if I can
improve this bug myself.

Thanks for the offer for the moment.

**Comment by fritogotlayed** [comment]
Ha, that's not a problem at all. You really shouldn't apologize for creating the issue since it would need to be tracked. As for the full time dev. job I completely understand. I have a full time job myself automating network configuration that really sucked my time away. I'm typically a C# developer but the job has me learning Python / linux so putting any effort into learning SQF hasn't really been high on my list, lol.

**Comment by ultranoobian** [comment]
I've tested sling loading in single-player, local multiplayer, and remote multiplayer. Sling loading does not appear to be misbehaving.

**Comment by jamwaddell** [comment]
It's all good man, I know how that is. I hope you get someone to cover this
mod eventually. You did a great job with it so far and it just needs some
tender loving care in the future. If I get free sometime when my job load
lets up to work on it I'll hit you up. Thanks for the work you have done.
