### ISSUE TITLE
Waiting for the host to find HQ when using dedicated server

### ISSUE THREAD

**Issue by phr0gz** [DUWS-R-Team/DUWS-R#12]
I cant chose anything when I start the mission on a dedicated server, I just have "waiting for the host to find HQ" but there is no menu...

ServerLog:

```
15:16:15 Error in expression <ignedItems player find "ItemGPS";
if (_number != -1 && !_player_has_gps) then >
15:16:15   Error position: <_number != -1 && !_player_has_gps) then >
15:16:15   Error Undefined variable in expression: _number
15:16:15 File mpmissions\__cur_mp.Stratis\misc\gps_marker.sqf, line 8
```

**Comment by fritogotlayed** [comment]
Hey @phr0gz 

Thanks for making the issue ticket to track dedicated servers not working with DUWS-R. Currently DUWS-R has not diverged far from the last release of DUWS and thus does not have fixes for many of the bugs yet. Currently running DUWS-R on a dedicated is not supported due to how the mission initializes. This is on our radar to complete but we need to come to a design decision on how to get there. 

The current work around is to play DUWS-R as a "listen" server. This is simply launching the DUWS-R mission from the multi-player menu item in Arma. You can then invite others to play directly. There is a known issue where it seems to take some time to have the squad selection screen appear before actually starting the DUWS-R mission. Once we can determine if this issue is definitely from DUWS-R it will be logged and worked in one of our sprints.

**Comment by phr0gz** [comment]
Hi fritogotlayed,

thx for this answer!

I hoped that this version would work with dedicated too, It does not cost anything to try :). Anyway is it possible to force the HQ to spawn in a random location as a workaround?

**Comment by fritogotlayed** [comment]
@phr0gz Haha. It doesn't hurt to try at all. 

A random HQ spawn location was what I was thinking but that only solves the tip of the iceberg. You also have other options that need to be accounted for: Starting CP, Starting blufor AP, Starting opfor AP, etc. While the easy option would be to just use the defaults I think this might only serve a small portion of the community. Another item I still need to research is how to tell when you're in a dedicated server vs a listen server. I really want to use a dedicated server as well so I may hop on this bug next. I  have a few more plumbing things to get squared away before I can get fully focused on bugs / feature work.

If you'd like to take a crack at it I feel free to fork the repo and make a pull request when you're ready. Part of the plumbing I mentioned earlier is to get the development process, tools, formatted code and misc items done so on-boarding other devs is pretty painless. I'm all about having more people work on DUWS-R b/c I think it'll be a better mission in the end for everyone :-) [The Developer Guide](https://github.com/DUWS-R-Team/DUWS-R/wiki/Developer_Guide) is a great place to start. 

I'll see if I can figure out a way to make a "next milestone" to get others interested as well!

**Comment by fritogotlayed** [comment]
@phr0gz I just realized you're going to have some serious merge issues if you were to actually start by forking this. I'm working on an effort to reformat all the code to a c-like formatting. You might want to wait until my next merge... I'm hoping to be done and merged this weekend but it may be next weekend.

**Comment by phr0gz** [comment]
Atm the game is partially working with dedicated and random hq placement isn't working:
Change l. 220 in the init.sqf:
if (isServer) then {
per
if (!isDedicated && !HQ_pos_found_generated) then {

If you quit the game you lose your Squad Lead leader radio unlocks.

**Comment by phr0gz** [comment]
For the armory in the dropped ammo crate:
Change l. 35 in the init.sqf:
if (support_armory_available) then {_ammo addaction ["<t ```color='#ff1111'>Armory</t>","VAS\open.sqf", "", 0, true, true, "", "_this == player"]};```
per
```if (support_armory_available) then {_ammo addaction ["<t color='#ff1111'>Armory</t>","VAS\open.sqf"]};```

**Comment by phr0gz** [comment]
Idea for persistent server protect Main HQ:
In BluHQinit.sqf
befor line 64
```// IF THE OFFICER IS DEAD -- BEGIN OF "SPAWN"```
add:
```//CREATE PATROL
_size = 5;
[_hqblu, _size] execvm "createoppatrolBlueHQ.sqf";
[_hqblu, _size] execvm "createoppatrolBlueHQ.sqf";```

Create file in the root directory "createoppatrolBlueHQ.sqf" with:

```// usage: [position, radius] execvm "createoppatrol.sqf"
// radius: 50 for patrol inside and around base, 500 for medium lenght skirmish, 1300 for island

_position = _this select 0;
_radius   = _this select 1;

// hint format["%1",_position];

_group = [_position, WEST, ["B_Soldier_F","B_Soldier_F","B_Soldier_AT_F","B_engineer_F","B_medic_F","B_recon_F","B_Soldier_AT_F"],[],[],[0.6,0.8,0.7]] call BIS_fnc_spawnGroup;
_patrolRadius = round(_radius/2);
[_group, _position, _patrolradius] call bis_fnc_taskPatrol;

//_skill = skill leader _group;
//player globalchat format["%1",_skill]; 

// ADD Infinite Ammo eventhandler
_group addEventHandler ["Fired",{(_this select 0) setvehicleammo 1}];```

**Comment by fritogotlayed** [comment]
@phr0gz Nice work. I haven't actually applied these changes. Have you thought about forking DUWS-R and making a PR back? It would definitely be safer than my hand coping the code around. Also, you'll forever be immortalized in our contributor history :-D. 

If you do decide to fork the repo I would create it either after this weekend or make it from my personal branch for [DUWSR-19](https://github.com/fritogotlayed/DUWS-R/tree/DUWSR-19). I'm going to be playing the changes I've made to ensure that with #19 I didn't break anything.

If you'd like I can give you a hand with that. I'm working on getting the [Developer Guide](https://github.com/DUWS-R-Team/DUWS-R/wiki/Developer_Guide) squared away. Also, we're trying to grow the team to some more experienced ArmA scripters so we can get some peer reviews in place and all that.

**Comment by phr0gz** [comment]
Ok no problem about the fork. I can  i will focus on the side mission tomorrow. and also the defense of the main HQ.

**Comment by fritogotlayed** [comment]
@phr0gz Sounds good. :-) Please assign the items you're working on to yourself. I tried adding you to the DUWS-R organization and it looks like you accepted but I can't actually assign the issue to you :-/. As the team grows I think it'll be easier to make sure we don't step on each others toes that way.

**Comment by phr0gz** [comment]
I dont have "assign yourself" :/

**Comment by fritogotlayed** [comment]
Ugh. I'm trying to figure it out. Feel free to hop on the IRC over on afternet.org. The web client is at https://kiwiirc.afternet.org/. It may be easier to coordinate there rather than on posts here. Plus it would help keep the conversation here clean :-) The channel is DUWS-R-Devs

**Comment by fritogotlayed** [comment]
Cleaning up the comments containing code in this issue.

**Comment by RoguePA** [comment]
Do we have a workaround for this yet? I tried setting it up today but didnt realise I needed a listen server not a dedi, working on a dedi would make this a million times better

**Comment by CaiusAjiz** [comment]
Just tested this on a dedi (windows, latest update) and it's working fine. I can't find the commit that sorted this but I recall seeing a fix from @ultranoobian ages back that fixed this.

**Comment by CaiusAjiz** [comment]
I've been using DUWS-R on a dedi for many years (Recently added to the DUWS-R org to be able to close issues), and it's been working since my comment in 2019. First player in is given the choice as to what to do with FOB and mission setup.
