### ISSUE TITLE
Checkpoints, additional or respawning security at HQ

### ISSUE THREAD

**Issue by fritogotlayed** [DUWS-R-Team/DUWS-R#13]
As the mission continues over time if Opfor patrols are strong enough they can eliminate infantry at the HQ. It may be worth creating checkpoints along routes that the enemy patrols take to the Blufor HQ. Another possibility is having a way to purchase HQ controlled reinforcements or having the existing reinforcements re-spawn after a certain time limit.  

### Reference
http://forums.bistudio.com/showthread.php?187877-SP-MP-Dynamic-Universal-War-System-Rebirth&p=2862555&viewfull=1#post2862555

**Comment by bolbies** [comment]
For checkpoints, maybe expand on the "Enemy near HQ" trigger. Once said enemies are gone, the game wait a couple minutes and then sends out three soldiers to the nearest road (I guess?) in facing the direction where the enemies came from. They'll set up sand bags, a static turret, and AT weapon. The third guy can be a sniper or something. That's all I've got for that. Respawning security wouldn't be a problem but what about the base itself? Should that be respawned as well or would that be too OP?

**Comment by fritogotlayed** [comment]
I wouldn't think that the base should be respawned. I like having a loose condition of the commander being killed. Having a way to fail (and thus the game being 'hard') is what makes winning fun.
