### ISSUE TITLE
Zeus not showing all units deployed and some big zones shows only a few units

### ISSUE THREAD

**Issue by abierce** [DUWS-R-Team/DUWS-R#139]
Hi. Maybe  I should have created two posts instead of one. I have been playing DUWS-R as well as DUWS-R+RHS for a while. This is an awesome mod. I've noticed a few things.

-When starting a mission and checking in zeus if everything's all right I've noticed that some zones (the bigger ones) sometimes appear a little empty. Aren't they supposed to have more troops?.
-Sometimes units are deployed that Zeus don't show up in the left panel. 

Is that normal?. I haven't touched anything inside the mod so I don't thing I've messed up anything.

Update: The zones that are empty right after creating them get troops after a while. It's like they take a little longer for troops to be spawned there.

**Comment by ultranoobian** [comment]
Sorry, Currently the current version (v0.5.1) does not support Zeus.

And yes, it does take a little amount of time for all the units to spawn because of ARMA 3 scheduler.

**Comment by abierce** [comment]
Ok. Thanx for your reply
