### ISSUE TITLE
Lighting around the HQ is poor at night

### ISSUE THREAD

**Issue by fritogotlayed** [DUWS-R-Team/DUWS-R#14]
There needs to be discussions around the PROs and CONs of having additional lighting around the HQ. I'm sure there are some players that wish for a stealthy and/or night-ops feel. Others could use additional lighting around the HQ at night.

### Reference
http://forums.bistudio.com/showthread.php?187877-SP-MP-Dynamic-Universal-War-System-Rebirth&p=2862555&viewfull=1#post2862555

**Comment by bolbies** [comment]
I tested out the lights listed here:
https://community.bistudio.com/wiki/Arma_3_CfgVehicles_EMPTY

The brightest lights are the camping lights which are already being used at the bases. I added four more lights to the mix and it didn't make a noticeable change in regards to brightness. We could easily add more literally around the base if that's what's wanted. Being able to turn them on or off shouldn't be too hard either.

**Comment by fritogotlayed** [comment]
I know you already have this pull requested but what about the additional lights being something you have to purchase. Much like the armory, artillery strike, mortar strike, etc.?

**Comment by bolbies** [comment]
I guess so? I was thinking the lights could be toggled for stealthy players for sure but I don't really see a point in buying a few more lights, at least for now. Maybe once we implement checkpoints we can buy more that will "smartly" spread themselves out to light up the entire base if that makes any sense.

**Comment by fritogotlayed** [comment]
I'm sorry. I think I was unclear. I was meaning that the lights you added had to be purchased. That comment was made completely out of my backside since I haven't pulled your branch and attempted to play test it yet. It's honestly not that big of a deal since if we decide that needs to be done we can always make another story in the future to tweak the behavior.

Thanks a ton for implementing this!
