### ISSUE TITLE
Command system broken while in vehicles

### ISSUE THREAD

**Issue by fir3f1ght** [DUWS-R-Team/DUWS-R#152]
The team command system is broken! When you're a vehicle passenger, and you have 2 trucks, both ai drivers, you if you tell the vehicle driver your in to go somewhere, he does. BUT the other truck that is supposed to FOLLOW, doesn't. if you tell him (Other truck driver) to regroup, it does nothing. But if you tell your own ai driver in your truck to regroup. He stops the car entirely and waits for the other car to catch up. Then they just sit there. PLEASE FIX THIS

**Comment by ultranoobian** [comment]
Hey, Thank you for putting an issue in the tracker.

Unfortunately, this is not a DUWS-R related problem, This is a Bohemia Interactive problem, I would suggest that you post on their feedback tracker @ http://feedback.arma3.com/
