### ISSUE TITLE
Manned APC Spawned inside Command building.

### ISSUE THREAD

**Issue by TuxuHolyland** [DUWS-R-Team/DUWS-R#153]
I've ordered a motorized inf unit in an APC, it spawned inside the HQ. http://steamcommunity.com/sharedfiles/filedetails/?id=970694107

Happened in a listening server multiplayer that I'd hosted on my own PC.

**Comment by TuxuHolyland** [comment]
Leave a comment

**Comment by ultranoobian** [comment]
Hey @TuxuHolyland , Thank you for submitting a bug report.

Just to ask some questions, Did you already have multiple vehicles spawned outside the HQ and/or did you spawn lots of groups at once?

**Comment by TuxuHolyland** [comment]
Hi, I've spawned the apc in an empty HQ That was situated east of Balota,
south of Balota's Airfield and very close to the asphalt road which was
several meters to the south of the HQ.
I've tried to recreate that on that map of Australia(from the workshop) and
have failed. I've placed HQ in an airport and tried to spawn that airplane
that has a tag saying "spawn only in an airfield" and it crashed the HQ as
it spawned.
Don't hesitate to ask for more info/pics as required, I'll be glad to be of
service.

Regards.

On Jul 11, 2017 14:27, "Brenden Cai" <notifications@github.com> wrote:

Hey @TuxuHolyland <https://github.com/tuxuholyland> , Thank you for
submitting a bug report.

Just to ask some questions, Did you already have multiple vehicles spawned
outside the HQ and/or did you spawn lots of groups at once?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DUWS-R-Team/DUWS-R/issues/153#issuecomment-314414674>,
or mute the thread

**Comment by ultranoobian** [comment]
Okay, I think I found the problem for quite a few things.
The code for spawning units, vehicles and groups doesn't implement safe spawn locations. It only offsets the HQ position by a few units and has static spawn point for the entire game.

So if you were to quickly spawn in a few vehicles, it would very quickly saturate the area and/or kick up some buildings.

In your case, the latter must have happened, and it spawned on the fence.

**Comment by TuxuHolyland** [comment]
assuming that the new safe spawns are implemented for groups and vehicles I'll give it a go in a day or two when I have a break from the uni.
