### ISSUE TITLE
FOB request does not appear when too many supports are purchased

### ISSUE THREAD

**Issue by ultranoobian** [DUWS-R-Team/DUWS-R#154]
FOB request will not appear in request menu if there are too many purchased support items.

This is due to the lack of pagination of the support menu by BIS

> [From Steam Forum](http://steamcommunity.com/workshop/filedetails/discussion/859325140/135509024340612464/?ctp=2#c2741975115080186460 
)> Could the FOB issue have something to do with your supports menu being full?  A friend hosted last night and unlocked all the supports; 0,8 menu, 1-0 were all full with UAV recon, Artillery, etc.  We cleared the first zone and there was no FOB option.  Same with a hard-fought second zone.
> 
> Tonight I hosted a MP server and only unlocked  a few supports, cleared the first zone, FOB was added to my supports menu after a few seconds.  Went back to HQ and unlocked all supports, then cleared second zone.  No FOB option appeared at all. 
> YES! That was an issue I wrote down in my notebook, Max is 10.

https://community.bistudio.com/wiki/Arma_3_Communication_Menu#Adding

**Comment by ultranoobian** [comment]
Will most likely circumvent this by creating a custom submenu in radio menus.

**Comment by TuxuHolyland** [comment]
I think that the various types of supports could be grouped, ammo, UAV and paratroopers to Ariel support.
All the airstrikes and artillery attacks could be also bunched into a ranged strikes category...

in that spirit...

**Comment by ultranoobian** [comment]
This is my attempt at creation a new menu system for Supports
https://github.com/ultranoobian/DUWS-R/commit/0d34aaf312b5843e24bd90bf8904a327301c95c3

It definitely frees up the Comm Menu and doesn't take up too many CPU cycles when it generates.

**Comment by CurePindal** [comment]
So, this is fixed in 0.6?

**Comment by ultranoobian** [comment]
Fixed and merged in #167
