### ISSUE TITLE
Custom loadout

### ISSUE THREAD

**Issue by MCS1** [DUWS-R-Team/DUWS-R#159]
Could this be integrated?

https://forums.bistudio.com/forums/topic/204747-release-gom-aircraft-loadout-v133/

Ps I have the carrier and more in my version, I can always send the code?

**Comment by ultranoobian** [comment]
Nice find, Yes it can be integrated but only when I have time to.

It's better if you make your own pull request for these sorts of things if you already have code ready, That's what makes it a community effort

**Comment by MCS1** [comment]
Thanks!

I should investigate github a little bit further how it all works. I'll try to do that so you could check it out. It's really a cool addition to the mission. 

I understand that you have a limited time. If you should have time, it would be AMAZING! my knowledge is too basic for this hehe

Have a great day!
