### ISSUE TITLE
I would like to add the CAS and Heli HC supports back into my version

### ISSUE THREAD

**Issue by LT-DANG** [DUWS-R-Team/DUWS-R#162]
Hey, I have built a lot of WW2 and one UNSUNG version of an older version of DUWS author = "Kibot / Modified by BigShot/ DUWS-R Team/ Z, however they are quite old versions and have a saving issue after reloading in COOP where the next zone you take ends the mission.  So i'm in the process of upgrading them all to the current DUWS-R.  
I noticed that the HC CAS and attack Heli supports have been taken out in these new versions.  I've made enemy planes spawn more regularly in my new WW2 version and kinda need the HC CAS and attack heli supports (I just change the attack heli support name to fighter support and the vehicle to a WW2 plane) to deal with the enemy planes/keep them occupied.  
I am wondering what the last version was that had them included so I can grab the code out of them and add it into my version.  I tried doing this from my older versions of DUWS but it didn't work as the supports coding is a bit different.   Hopefully the code hasn't changed so much that this isn't possible anymore.  Thanks.

**Comment by ultranoobian** [comment]
For record keeping
Issue has been discussed off github and done on a fork:
https://github.com/ultranoobian/DUWS-R/commit/fd3731889356593a1a8b885adde94cb565cc2e63

Won't implement and merge on main line.
