### ISSUE TITLE
No FOB option on dedicated servers

### ISSUE THREAD

**Issue by CurePindal** [DUWS-R-Team/DUWS-R#175]
I get no option to establish a FOB on a dedicated server after capturing a zone and clearing it.
Not sure if its related to https://github.com/DUWS-R-Team/DUWS-R/issues/173

**Comment by zbbErr** [comment]
I do so then captured 

[player,"fob_support"] remoteExecCall ["BIS_fnc_addCommMenuItem", 0, true];
