### ISSUE TITLE
Have you forgotten the (SP) origins of DUWS?

### ISSUE THREAD

**Issue by ameXumm** [DUWS-R-Team/DUWS-R#179]
Let me start by saying, i'm not the type to rant & rave, but here i am creating an account to possibly do just that,because i'm one of those people who mostly play Arma 3 Singleplayer, yes a mythical SP player, i play almost exclusively DUWS albeit programmatically modified variants for various mods and other community made SP scenarious.

And you recently saw fit to remove features that made DUWS so greatly enjoyable in single player, while adding features that logically make it more enjoyable for Multiplayer setups, such as rightly removing Excessively Overpowered & 'cheap' supports but also removing High Command Supports, especially High Command Transport, Attack Helicopters & Tank Platoons effectively making combined arms warfare with AI impossible, and you remapped 0-0-0 to a new radio code whilst additionally allowing saves from the ingame Save Menu,a little but irritating thing,not to mention you actually had an update where the AI that initialise as player squad memebers on init where not removed after WARCOM initialises in SP, which leads me to believe youre orienting towards multiplayer and away from the vast majority of players who perceive DUWS as the goto Scenario in single player.

Now i understand there's plenty of DUWS variants, but this is the only actively maintained one, and it's fast discarding any resembles to DUWS with the exception of it's name, my issue is philosophical, i can always modify my copy to my tastes,but not everyone can and i suppose what 'triggered me' was seeing this MP infatuation transition in to a part of my routine(waging war on a random island,with a vast army under my command),i.e where i least expected it.

**_And as a counter to my seemingly useless post_**,

 i have a tested concept that i think would take DUWS up a notch, the concept of **dynamically loading classes** to allow playing as different factions or loading in mod assets(factions) has been referenced in this very issue tracker, i actually recently tested my version of DUWS by rlex [https://github.com/rlex/a3-duws-unofficial](url)  using the 'Faction Data Extraction Script' from this other mod Dynamic Recon Ops [https://steamcommunity.com/workshop/filedetails/?id=722652837](url) that i should add also abandoned AI compatible revive system with a multiplayer only Vanilla Revive system, but has a nifty feature that allows dynamically retrieving faction data from all loaded mods, i think it's a much needed feature for DUWS that WORKS, just check it out at least, i'm a mediocre scripter so i even used the DRO GUI to select factions and simply populated the DUWS classes with the output of the script,and viola i can play any faction against any other faction.

And as for my original issue,i highly suggest simply raising the cost of HC supports instead of doing away with them altogether, Arma 3 is a combined operations game,but it's also a single player game,i really think you should even consider transitioning Non-existent supports to On Map AI supports, instead of doing the reverse where the player has support assets that are virtually invulnerable and limited only by CP, and possibly even add unit loss CP penalties so that player doesn't use AI as assets to be discarded..,

Additionally for your consideration of a feature to add, my modified DUWS also uses HETMAN by  Rydygier [https://forums.bohemia.net/forums/topic/158157-hetman-artificial-leader/](url) to supplement WARCOM by simply dynamically creating and reordering markers for HETMAN at every generated Zone ranked by type of zone and capture status.

**Just my two-cents, cheers, and i mean no hostility, just stating my thoughts on an ideal(SINGLE PLAYER GAMERS STILL EXISTS), this wasn't about just some stupid scenario that i so very love...**

**Comment by ultranoobian** [comment]
Hey ameXumm,

Thank you for your write up on this. I'll try to respond to all of your points by breaking your post into smaller sections, and I'm not trying to be mean or anything when I do.

**Comment by ultranoobian** [comment]
> And you recently saw fit to remove features that made DUWS so greatly enjoyable in single player, while adding features that logically make it more enjoyable for Multiplayer setups, such as rightly removing Excessively Overpowered & 'cheap' supports but also removing High Command Supports, especially High Command Transport, Attack Helicopters & Tank Platoons effectively making combined arms warfare with AI impossible

In my honest memory, I have never seen High command supports in the DUWS-R code since I started restarted development in early 2017. And I don't know which other supports I have removed.
[This file history contains all the support items you could ever purchase and you see I have only recently edited it](https://github.com/DUWS-R-Team/DUWS-R/commits/master/source/support/support.hpp)

However! I did make a barebones reimplementation once for @LT-DANG in #162 

> and you remapped 0-0-0 to a new radio code 

Yes, I did change the support menu and I did that for a very good reason. #135, #154 
When you purchase too many supports (>9), you immediately break the scenario because the FOB support option won't be able to load anymore. And there wasn't any way to fix that after that had happen, no removal of purchased supports, or re-adding of the FOB option.

If you were the kind of player like some I know, you would never had encountered the bug because you were the kind of person who didn't typically use many supports, but for the people who do, they made it vocal.

> whilst additionally allowing saves from the ingame Save Menu

Again, I haven't changed anything to do with the [ingame save](https://github.com/DUWS-R-Team/DUWS-R/commits/master/source/utilities/autoSave.sqf), 
Multiple saves are a game option under 
`Game -> Difficulty -> Allow multiple saves`

> ,a little but irritating thing,not to mention you actually had an update where the AI that initialise as player squad memebers on init where not removed after WARCOM initialises in SP, 

If I put out a recent update where that happens, please tell me, because I need to fix that.

> which leads me to believe youre orienting towards multiplayer and away from the vast majority of players who perceive DUWS as the goto Scenario in single player.

Okay, here is where it gets messy!
DUWS-R was written millenia ago, relatively speaking, and it's not that it hasn't really aged well or that it performs poor (read: #161, #164, #150, #146, etc...) but maintainability has been an issue.

Part of the solution of solving that problem is maintaining compatibility between SP and MP. Me speaking, I feel that coding for MP then porting to SP is much more simpler than SP to MP.
However, I don't see how it has become an infatuation, because when I actually see the pull requests that I have actually merged with the mainline, Most of those have been feature updates to bring DUWS up to new DLC, or to fix old bugs.

* v0.3.0 - Merged dedicated from @phr0gz, and updates to subsystems
* v0.4.0 - Added EWS for missiles and various bug fixes
* v0.5.0 - Fatigue system is a thing now, added that as a option to multiplayer lobby
* v0.5.1 - more bug fixes
* v0.5.2 - More bugfixes  and added new 100,000 CP starting option
* v0.5.3 - Lots of more fun stuff, like not getting executed by your own AI, adding Jets DLC plans, fixing more bugs, and refactoring some old code.

So with that summary, I really don't understand where the obsession with MP is, I really just see it as maintenance.

**Comment by ultranoobian** [comment]
For the second half of your post, It isn't an issue of what to use to add factions and units and other cool stuff, Its how to integrate it into how DUWS already does things the way it does.

People have suggested on numerous occasions for AI mods, vehicle mods, Faction mods, etc..... But the whole underlying issue with all of them, is simply, I'm a part-time maintainer, I don't have the time integrate something which I haven't got the time to test.

And I've said it to all those people, if they give me a solution that's working and testable, then I will graciously accept their pull request.

**Comment by ameXumm** [comment]
Thank you, for a considered reply, here's mine:

> In my honest memory, I have never seen High command supports in the DUWS-R code since I started restarted development in early 2017. And I don't know which other supports I have removed.

I know, that's what i was referring to,i always add HC supports to your releases.

> Yes, I did change the support menu and I did that for a very good reason. #135, #154
When you purchase too many supports (>9), you immediately break the scenario because the FOB support option won't be able to load anymore. And there wasn't any way to fix that after that had happen, no removal of purchased supports, or re-adding of the FOB option.

> If you were the kind of player like some I know, you would never had encountered the bug because you were the kind of person who didn't typically use many supports, but for the people who do, they made it vocal.

Hmmm, my mistake, i really never use more than 5 supports(HC Attack, HC Trans,vehicle refit, UAV recon, supply drop), i use on map artillery units.


> Again, I haven't changed anything to do with the ingame save,
Multiple saves are a game option under
Game -> Difficulty -> Allow multiple saves

I know i can disable from settings, but how it previously worked was after the first autosave, in game save was disabled, such that anytime you exit a mission you'd have to resume from your last autosave,but in DUWS-R i can resume from where ever i left off('save & exit' instead of abort), which really only bums me out,so i 'endmission' it to force an abort. So it's no big deal, just something i noticed... Try running rlex version here on github that has more of the original code,saving works as described here. Again not a big deal.


> If I put out a recent update where that happens, please tell me, because I need to fix that.

You actually already fixed it, it was one of the late 2017 updates under a broad non-default startup condition i don't recall, the current update is the first update i checked since that, and it seems to work just fine.

> Okay, here is where it gets messy!
DUWS-R was written millenia ago, relatively speaking, and it's not that it hasn't really aged well or that it performs poor (read: #161, #164, #150, #146, etc...) but maintainability has been an issue.

> Part of the solution of solving that problem is maintaining compatibility between SP and MP. Me speaking, I feel that coding for MP then porting to SP is much more simpler than SP to MP.
However, I don't see how it has become an infatuation, because when I actually see the pull requests that I have actually merged with the mainline, Most of those have been feature updates to bring DUWS up to new DLC, or to fix old bugs.

    v0.3.0 - Merged dedicated from @phr0gz, and updates to subsystems
    v0.4.0 - Added EWS for missiles and various bug fixes
    v0.5.0 - Fatigue system is a thing now, added that as a option to multiplayer lobby
    v0.5.1 - more bug fixes
    v0.5.2 - More bugfixes and added new 100,000 CP starting option
    v0.5.3 - Lots of more fun stuff, like not getting executed by your own AI, adding Jets DLC plans, fixing more bugs, and refactoring some old code.

> So with that summary, I really don't understand where the obsession with MP is, I really just see it as maintenance.

Well the thing is, DUWS-R like all DUWS variants provides solutions to most of the problems i 'bitched' about here, such as using the squad manager to set a Transport/Attack helicopter crew as an HC squad from ones own squad, it's more in the design choices that i think,where the MP leanings are expressed, and i understand it's much more time efficient to adapt MP code to SP with far less possible issues arising, i just think at the feature level at least, though i have no feature requests outside of those that I've already 'mediocre-ly' implemented, i would just ask that you consider the value of a feature in SP before removing it for the sake of MP,and i'm not merely referring to things removed during the course of updates, but to things that were also removed at the outset of this fork, such as certain supports, gameplay mechanics i.e I'm hardpressed to think of a time when i last encountered active enemy vehicles(random_veh_opf_patrol.sqf),though i give the enemy generous AP on start, not to mention the lack of enemy air assets despite the anti-air emplacements at roof of every FOB.

So i guess what i'm saying is, I'm down with design choices already made for this fork, i just hope you don't continue this trend of adding awesome mechanics updates like 'being able to replace defenses' which is simple but valuable, and removing awesome features that add more value to SP replay-ability as those mentioned above, and many more little things that i'd rather not nitpick, just play another DUWS variant such as DUWS unofficial(rlex) or the original DUWS by kibot, and comeback to DUWS-R and you'll see what i mean, it's just starting to feel like your omitting as much as your adding,it's just what your adding is geared towards enhancing MP gameplay at the expense of SP **REPLAYABILITY**.

I will concede Combined Arms Warfare in SP isn't as lacking as i portrayed, however, there's practically no purpose for it, given the lack of comparable enemy assets, i can still steamroll Stratis in less than 30minutes,but i don't want to be able to do that is what i mean, so please when adding/removing features consider SP replay-ability,because in MP there's more choices to be had in how one plays DUWS, not so in SP.

> And I've said it to all those people, if they give me a solution that's working and testable, then I will graciously accept their pull request.

I'll try to clean up my code, test it a bit more and post it as an attachment on the issue tracker, i hate the github push-pull system. Talk is cheap,so I'm going to put my code where my mouth is, if that's a valid expression :) .


_**And i would like to thank you guys for the time you put into this,because i understand this is a pastime to you guys, as is playing it for players like me, SO THANKS for your awesome contribution.**_
