### ISSUE TITLE
Re-Arming Greyhawks

### ISSUE THREAD

**Issue by Alias-Me** [DUWS-R-Team/DUWS-R#183]
Supposedly I should be able to re-arm UAVs by activating the Vehicle Refit support while in the terminal, yet I always receive the message that I must be sitting inside of a vehicle to refit it, no matter im im just in the terminal, in the pilot position or in the gunner position.
The Greyhawk is right next to HQ and Im standing right net to it, any Ideas?

**Comment by ultranoobian** [comment]
Vehicles and Remote controlled vehicles must be within 100m of the HQ marker to be able to use the Vehicle Refit support.

Double check that your greyhawk is within that distance, while connected to your UAV terminal.
