### ISSUE TITLE
Host looses squad command randomly

### ISSUE THREAD

**Issue by fritogotlayed** [DUWS-R-Team/DUWS-R#32]
[unforgiven91](http://forums.bistudio.com/showthread.php?187877-SP-MP-Dynamic-Universal-War-System-Rebirth&p=2868722&viewfull=1#post2868722) reported that squad command is lost by the host during play. I have experienced this issue as well. This seems to be tied to player death. 

This may be tied to #27

Steps to reproduce can be found here: http://forums.bistudio.com/showthread.php?187877-SP-MP-Dynamic-Universal-War-System-Rebirth&p=2871223&viewfull=1#post2871223

EXPECTED OUTCOME
After the player dies occasionally they will lose the privileges they started the game with.

**Comment by lghenk** [comment]
I Can confirm this, they also randomly started shooting on me too which is really annoying :(

**Comment by ultranoobian** [comment]
https://github.com/DUWS-R-Team/DUWS-R/commit/636f60065c7a581c54cdee7d622c2b9680421346 handles spontaneous lost due to teamkills and damage

**Comment by ultranoobian** [comment]
https://github.com/DUWS-R-Team/DUWS-R/commit/4b2af98beb5afd6cabbb52d94a1de659ccf4dbe9 handles resetting group leader statuses
