### ISSUE TITLE
Why base from kibot's?

### ISSUE THREAD

**Issue by rlex** [DUWS-R-Team/DUWS-R#57]
I mean, there is modified version already with loads of features.

EDIT (Frito): http://www.maddonkeysoftware.com/DUWS-R/rlex_duws_mod.zip

**Comment by fritogotlayed** [comment]
Honestly, the Kibot version was the only one I knew of to start with. I came to know of DUWS from Steam Workshop. After I did maybe an hour of research the only other versions I had heard of were RHS Escalation and Bigshots. 

I felt there was a little too much drama around the Bigshots version with the whole pay-for / donation thing that was trying to be done. certain members of my family provide me enough headache and I didn't want to deal with that. For the RHS version, I honestly like, and wanted to support, a dynamic mission using the vanilla assets. While having mod unit support is on the road map I still want the vanilla experience present for those that want it. That and having less dependencies makes for a smaller download for players in low bandwidth situations.

The last big reason was that having the base maintained again might encourage other teams to also bring their mods under source control in github where it would be easier to share fixes in between them. This might be a pipe dream for me but I like having the "code" out there for people to find the flaws and help make better. After all, Kibot made a great starting point. It may be rough around the edges but with a little cleanup I think it will be easy to maintain in the future.

**Comment by fritogotlayed** [comment]
@rlex I am going to leave the question open for a couple more days in case you have any follow up questions. I'll most likely close it this weekend unless we continue the discussion. :smile:

**Comment by rlex** [comment]
Forking from kibot will be just a huge step backwards. 
You will need to implement huge set of features that was already implemented in modified. 
I feel same way, especially since i answered loads of questions, submitted couple of patches and so on. 
I even had my own fork of DUWS modified at time bigshot was away from coding.

Mod support is different theme.

Here is latest DUWS modified, btw www.mediafire.com/download/kgw28gpmzmsbf7d/%28duws%29%2520dynamic%2520universal%2520war%2520system%2520modified.altis.pbo

**Comment by fritogotlayed** [comment]
Heh, I hear ya on the re-implementing bit. We already have some mods in master right now so I might dedicate a sprint to just pulling in the changes from the mod version you linked. Do you know if dedicated server support is included in the mod version you posted?

**Comment by rlex** [comment]
No, DUWS was never intended to be running 24/7 on public servers. That will destroy gameplay.
Some hacks was implemented to pre-define answers on load questions as workaround. Was working. Sorta.
Here is my version also http://steamcommunity.com/sharedfiles/filedetails/?id=285488366
I can try to port that features (some of them, like missions, is just copy & paste)

**Comment by fritogotlayed** [comment]
I agree that it was never meant to be running 24/7. There have been a few asks for it though. Plus I can understand the desire to have it run on a separate machine from the one players are running on just to distribute some of the load. 

If you don't want worry with porting the features that's fine. I honestly would like to have them broken out into separate pull requests just to have it a little cleaner. I like to release smaller change sets just so it's easier to track things down and all that. I realize the work you have is already done and people are playing it but the DUWS-R Team is going to have to support it going forward.

On a somewhat related note if you're interested we are always looking for team members. We're operating on a lite scrum-like model. Basically whatever gets done in a month time box makes it into the next release.

**Comment by fritogotlayed** [comment]
Sorry about the ambiguity there... I was also eating. I meant to say that I would un-pack your PBO and try to break the changes apart into featured pull requests.

**Comment by fritogotlayed** [comment]
For simplicity sake I uploaded the PBO that @rlex linked to MadDonkeySoftware so when the mediafire link goes down we still have it.

**Comment by rlex** [comment]
Related licensing issues:
DUWS was licenced by CC3 BY-NC-SA, meaning DUWS Modified must use same licence, which 
1) prevents commercial use (useless for us)
2) revokes distribution control over product from both kibot and BigShot (meaning we can safely use recent available version from BigShot as base)
