### ISSUE TITLE
Ability to re-arm drones

### ISSUE THREAD

**Issue by fritogotlayed** [DUWS-R-Team/DUWS-R#72]
Per Nick on Steam Workshop, the ability to re-arm drones is missing. I'm not 100% sure if this is from the original DUWS from Kibot or from the mod version produced by BigShot. Since we are slowly pulling in the changes from BigShots pbo once we can verify them, this issue may need to be addressed after that. 

```
Does this version feature a fix for the problem where u couldnt re-arm drones? Because right not
its impossible to re-arm drones using "vehicle-refit" because u cant actually sit in it and it 
wont recognize it. (Section omitted). Good work on this mod so far!!
```

**Comment by rlex** [comment]
I was able to refill drones when i was "sitting" at pilot position via UAV terminal.

**Comment by ultranoobian** [comment]
UAVs can be rearmed by going into terminal, and having the Unmanned unit at an appropriate distance from the HQ will allow the 'Vehicle Refit' support to work.

This was implemented in https://github.com/DUWS-R-Team/DUWS-R/commit/d71ddd31eac4ed6418ac4e01c5b7688ef07d135d
