### ISSUE TITLE
Vehicle spawn inside the command center

### ISSUE THREAD

**Issue by Falcata** [DUWS-R-Team/DUWS-R#99]
If you get a Ghost Hawk helicopter at the command center just when you finish the setup of the mission, the generated helicopter spawned inside the command center and create a big explosion.

This issue begins just after ask another helicopter like black foot.

**Comment by fritogotlayed** [comment]
I looked into this a bit and I'm not sure how to fix it just yet. I did not get the explosion as mentioned in the description but I did get a clipping issue from a second helicopter and the base intersecting.

**Comment by dgrrr** [comment]
This is probably unrelated, but in vanilla DUWS (not rebirth), I noticed that when the game AI spawned in new friendly vehicles (i.e. not at my request), it did so top of a pre-existing burned out vehicle. This caused explosion, killing the CO. So I used another vehicle to push the dead one out of the way, and this fixed the issue.

**Comment by ultranoobian** [comment]
We can use this https://community.bistudio.com/wiki/findEmptyPosition to check for empty space. This would solve the issue of having vehicles spawn on top of vehicles.

I know that from the APEX update, the STOL Blackfish's have huge models and will often clip other terrain and even more so, itself, if you spawn more than one.

**Comment by ultranoobian** [comment]
Issue fixed in https://github.com/DUWS-R-Team/DUWS-R/commit/354ad3bebeeaa208ae39d963bc823251a7cf3857
